version: "2"
linters:
  enable:
    - depguard
    - testifylint
    - unconvert
  disable:
    - revive
    - staticcheck
    - unused
  settings:
    depguard:
      rules:
        forbid-pkg-errors:
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced with standard lib errors or fmt.Errorf
    errcheck:
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (github.com/go-kit/log.Logger).Log
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kubeservice-stack/echo)
        - prefix(github.com/kubeservice-stack/common)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
