version: 1
timeout: "1m"

explicitLocalValidators: true

validators:
  # Skip localhost examples.
  - regex: 'localhost'
    type: "ignore"
  # docs.github.com returns 403 if not in browser. Cannot curl as well.
  - regex: 'docs\.github\.com'
    type: "ignore"
  # Cloudflare protection, so returns 503 if not in browser. Cannot curl as well.
  - regex: 'wise\.com'
    type: "ignore"
  # Adopters example link.
  - regex: "our-link"
    type: "ignore"
  # 301 errors even when curl-ed.
  - regex: "envoyproxy"
    type: "ignore"
  # Ignore links to /img/ because the generated content will resolve them correctly.
  - regex: '/img/.+'
    type: ignore
