name: Assets
on:
  workflow_dispatch:
  push:
    branches:
      - 'release-*'
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: git-branch
        run: |
          echo "git-branch=$(echo ${GITHUB_REF##*/} | tr '[A-Z]' '[a-z]')" >> "$GITHUB_OUTPUT"
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ env.golang-version }}'
          check-latest: true
      # Build binary
      - name: Build
        run: make build-assets
        env:
          PUSH: ${{ github.event_name != 'pull_request' }}
      - name: Release
        # https://github.com/softprops/action-gh-release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/*
